name: Manual
on:
  workflow_dispatch: # 手動実行イベント
    inputs:
      greeting: # 入力パラメータ名
        type: string
        dafeult: "Hello"
        required: true
        description: "A cheeful world"
jobs:
  run: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}, world!"